name = "Season 8 Modpack Lite"
author = "kamaii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09eb90dba065049a61cbdfb8d30bb06acb0967cc48c22e8a5bcdabbe23c41e0c"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
