name = "Season 8 Modpack Kamaii Edition"
author = "kamaii"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c34382b1461bc10955d36602b1f05364a8c82de1fa9a69db913ec7bc55f6c0b"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
