name = "NearLava 1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fc1e5aa06f679b2b1f6d1f3660bfe58873ba0dc79f86ba72b3423e15d1079cb"

[versions]
fabric = "0.14.14"
minecraft = "1.19.2"
